name: build-windows
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller pywebview

      - name: Build portable EXE
        run: pyinstaller packaging\bitd_gm_ai_win.spec --noconfirm

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build installer
        run: iscc packaging\installer.iss /DAppVersion=1.0.0

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: BitD_GM_AI_Setup
          path: dist\installer\BitD_GM_AI_Setup.exe

      - name: Upload portable app
        uses: actions/upload-artifact@v4
        with:
          name: BitD_GM_AI_portable
          path: dist\BitD_GM_AI\
