name: build-windows
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PYTHONDONTWRITEBYTECODE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree
        run: |
          echo Files in repo:
          git ls-files

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller pywebview

      - name: Build portable EXE (PyInstaller)
        shell: pwsh
        run: |
          pyinstaller packaging\bitd_gm_ai_win.spec --noconfirm --clean --log-level DEBUG *>& build_pyinstaller.log

      - name: Upload PyInstaller log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build_logs
          path: |
            build_pyinstaller.log
            **/warn-*.txt

      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup -y

      - name: Build installer (Inno Setup)
        shell: pwsh
        run: |
          $iscc = "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"
          & "$iscc" packaging\installer.iss /DAppVersion=${{ github.run_number }}

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: BitD_GM_AI_Setup
          path: dist\installer\BitD_GM_AI_Setup.exe

      - name: Upload portable app
        uses: actions/upload-artifact@v4
        with:
          name: BitD_GM_AI_portable
          path: dist\BitD_GM_AI\

      - name: Upload dist (always, for diagnostics)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist_raw
          path: dist\
