name: build-windows
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PYTHONDONTWRITEBYTECODE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree (sanity check)
        shell: pwsh
        run: |
          git ls-files | Out-String | Write-Host
          if (-not (Test-Path "run_app.py")) { Write-Error "run_app.py not found in repo"; exit 2 }
          if (-not (Test-Path "app\server.py")) { Write-Error "app\server.py not found in repo"; exit 2 }

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller pywebview

      # Сборка БЕЗ .spec: один exe из run_app.py, с ресурсами папки app
      - name: Build portable EXE (no-spec)
        shell: pwsh
        run: |
          pyinstaller --noconfirm --clean --log-level DEBUG `
            --name "BitD GM AI" `
            --noconsole `
            --icon "packaging\bitd_gm_ai.ico" `
            --add-data "app;app" `
            run_app.py
        # если упадёт — выложим всю директорию build
      - name: Upload build logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build_logs
          path: |
            build\
            *.log

      - name: Upload portable app
        uses: actions/upload-artifact@v4
        with:
          name: BitD_GM_AI_portable
          path: dist\BitD GM AI\

      # Инсталлятор Inno Setup (используем собранную папку с пробелом в имени)
      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup -y

      - name: Build installer
        shell: pwsh
        run: |
          $iscc = "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"
          & "$iscc" packaging\installer.iss /DAppVersion=${{ github.run_number }} /DSourceDir="dist\BitD GM AI" /DOutputDir="dist\installer"

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: BitD_GM_AI_Setup
          path: dist\installer\BitD_GM_AI_Setup.exe
